apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "external-dns-target-admission.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "external-dns-target-admission.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "external-dns-target-admission.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
